### ISSUE TITLE
PS 1.7.7.5 - Error after install: unknown tag 'generateImagesSources'

### ISSUE THREAD

**Issue by fofoy** [Oksydan/modern-prestashop-starter-theme#39]
Hello,

I tried to install this theme earlier and encountered the following error after the install in FO:
`/public/themes/starter/templates/catalog/_partials/miniatures/_partials/product-thumb.tpl" on line 7 "{generateImagesSources image=$product.default_image size='home_default'}" unknown tag 'generateImagesSources'`

Btw great work with this theme, it seems great, really looking forward using it in the future.

**Comment by Oksydan** [comment]
HI @fofoy,

you have to install required modules https://github.com/Oksydan/modern-prestashop-starter-theme#modules-required.
`GenerateImageSources` is smarty function registered in is_themecore module https://github.com/Oksydan/is_themecore/blob/main/classes/SmartyHelperFunctions.php. 
Required modules are not inside theme export because I am able to make separate releases for modules/theme.

Thank you about kind words.

**Comment by fofoy** [comment]
Hi @Oksydan, I installed it but now I understand what's wrong now.

I just downloaded the last release from every module, therefore they seem outdated compared to the `main` branch, I'll download them from the `main` branch from now on.

Thanks !

**Comment by Oksydan** [comment]
@fofoy 
I made new release https://github.com/Oksydan/is_themecore/releases/tag/v1.1.1
It was my bad. I forgot about releasing dependencies modules.

I think we can mark it as closed. 
If you will face any problem. Create an issue I will be glad to help.

**Comment by fofoy** [comment]
Thanks for your help!
