### ISSUE TITLE
🐛 [BUG] - is_favoriteproducts module don't hook and show properly 

### ISSUE THREAD

**Issue by qwebdevel** [Oksydan/modern-prestashop-starter-theme#421]
### Description

I add properly module in theme.yml and hook in DisplayTop only way for this module to work is reset and hook manually in backend to properly display in top.

### Node.js version

v1.4.10

### php version

8.1

### OS and it's version

Windows 10

### Browsers

Firefox, Chrome, Opera

### Required module/theme

is_favoriteproducts

### Reproduction steps

```bash
1. Go to 'theme.yml add on dependies hook on DisplayTop'
2. Click on 'import theme'
3. Scroll down to 'use theme'
4. See error
```

**Comment by Oksydan** [comment]
Hi @qwebdevel,

this module is optional, that's why it isn't exists in the theme.yml file. You should install it right after theme installation, otherwise your hooks in for example displayTop with be unregistered. I feel like we don't have to do anything here 🤔. I am closing this issue, feel free to open reopen or open new one.
