### ISSUE TITLE
🐛 [BUG] - Brak zmian po wprowadzeniu tytułu, opisu SEO kategorii

### ISSUE THREAD

**Issue by Spasio** [Oksydan/modern-prestashop-starter-theme#433]
### Description

Po wprowadzeniu zmian tytułu, opisu, słów kluczowych SEO z pozycji kategorii zmiany te nie są uwzględniane na front-office. Tytuł strony i opis w dalszym ciągu pozostaje "domyślny". Czy ktoś spotkał się z takim problemem i wie w jaki sposób można go rozwiązać, tak aby po wprowadzeniu zmian z pozycji kategorii lub produktu zmiany były widoczne? 

### Node.js version

v.15.0.0

### php version

v8.1

### OS and it's version

Macos/Windows

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### Required module/theme

is_themecore or theme

### Reproduction steps

```bash
1. Go to 'Homepage -> random category'
2. Check Meta title, Meta Description, Meta Keywords,
3. Go to 'Backoffice -> Catalog -> Categories' Edit Category adding Meta Title, Meta Description, Meta Keywords
4. Back to 'Homepage -> Edited Category'
5. Check the meta title, meta description, meta keywords.
```

**Comment by Oksydan** [comment]
Hi @Spasio,

We communicate in this space in English. Please create an issue in proper language.
If changes aren't visible in FO of your store, there must be a cache somewhere. 
Are you using full page cache module, varnish, lightspeed cache or some kind of cache/speed optimization module?
This issue is 100% not related to the theme but your instance itself.
I am closing this issue. Feel free to open a new one.
