### ISSUE TITLE
Product swiper stopped working

### ISSUE THREAD

**Issue by lucrp** [Oksydan/modern-prestashop-starter-theme#61]
Hello !

For some reason, products swiper stopped to work. I could not swipe products clicking next and prev icons. Also, I had this error message from console :
![image](https://user-images.githubusercontent.com/6523221/146573143-1dee6751-6d98-4128-847b-fbf5c6fd7a5c.png)

So in `PageSlider.js` I removed `&& typeof elConfig.navigation === 'undefined'` from this if statement:
```
    if ($nextEl.length && $prevEl.length && typeof elConfig.navigation === 'undefined') {
      elConfig = {
        ...elConfig,
        navigation: {
          nextEl: $nextEl[0],
          prevEl: $prevEl[0],
        },
      };
    }
```

And now it works. :) But I'm not sure if it's a bug.

**Comment by Oksydan** [comment]
Hi @lucrp,
looks like you created template for swiper slider but you didn't included `data-swiper` to `.swiper-container` block.
By removing this code, swiper slider initialization aren't going to automatically set navigations arrows to slider.
It isn't bug but since if `swiper-container` class exists on slider but w/o `.swiper-container-custom` it will be automatically initialized with `PageSlider` class.
I had added default value for that `elConfig` to prevent any error here https://github.com/Oksydan/modern-prestashop-starter-theme/commit/ec7e532f27563d5349d4e51b973ee6e44da08492
It will be available in next release.
Please check and feedback.

**Comment by Oksydan** [comment]
HI @lucrp,
I am closing this issue since problem should be resolved.
