### ISSUE TITLE
How to reuse swipper ?

### ISSUE THREAD

**Issue by RTDC** [Oksydan/modern-prestashop-starter-theme#64]
Hello,

Can you tell me how to reuse Swipper JS to create a slider like for product thumbnails?

Exemple : 
```
<div class="swiper">
  <div class="swiper-wrapper">
    <!-- Slides -->
    {foreach $instagram_pics as $pic}
        <div class="swiper-slide">
          <a href="{$pic.link}" title="{$pic.caption|escape:'html':'UTF-8'}" target="_blank" rel="nofollow">
            <img src="{$pic.image}" alt="{$pic.caption|escape:'html':'UTF-8'}" class="img-responsive" />
          </a>
        </div>
    {/foreach}
  </div>
```

Thank's :)

**Comment by Oksydan** [comment]
Hi @RTDC,
it is required to use `data-swiper` attribute to initialize swiper with parameters. 
You have to use `swiper-container` instead of `swiper` class since we are still using version 6 not 7, `data-swiper` accepts all swiper [parameters](https://swiperjs.com/swiper-api#parameters).
Example: 
```html
{$sliderConfig = [
  'speed' => 500,
  'breakpoints' => [
    '320' => [
      'slidesPerView' => 2
    ],
    '768' => [
      'slidesPerView' => 3
    ],
    '992' => [
      'slidesPerView' => 4
    ],
    '1200' => [
      'slidesPerView' => 5
    ]
  ]
]}
<div class="swiper-container" data-swiper="{$sliderConfig|json_encode}">
  <div class="swiper-wrapper">
    <!-- Slides -->
    {foreach $instagram_pics as $pic}
        <div class="swiper-slide">
          <a href="{$pic.link}" title="{$pic.caption|escape:'html':'UTF-8'}" target="_blank" rel="nofollow">
            <img src="{$pic.image}" alt="{$pic.caption|escape:'html':'UTF-8'}" class="img-responsive" />
          </a>
        </div>
    {/foreach}
  </div>
 ```
 To disabled swiper auto initialize, you have to add class `swiper-container-custom` to `swiper-container`.

I am thinking about dropping swiper in favor of [splide](https://github.com/Splidejs/splide) in next major version.

**Comment by RTDC** [comment]
Thank you for everything !
I tried without success with the doc :)

Thank you for taking the time to help and quickly,

Best wishes for 22

**Comment by Oksydan** [comment]
Since problem is resolved I am closing this issue.
If you find any trouble with starter, open another issue and I will try to help.
If you like this project give it a star. It helps me stay motivated to improve it.
