### ISSUE TITLE
shop not loading after activation of theme

### ISSUE THREAD

**Issue by kennethbruyninckx** [Oksydan/modern-prestashop-starter-theme#65]
PS 1.7.7.5

After copying the required modules (latest version) and installing the theme I visit the shops URL and got nothing.
Turned on debug mode and revisited the shops URL and got this:

![image](https://user-images.githubusercontent.com/63542736/147892711-e1397240-59db-4ad1-9bfe-ad0407ebde2a.png)

What did I do wrong?

**Comment by Oksydan** [comment]
Hi @kennethbruyninckx,
thank you for your report.
Are you sure that file `modules/is_themecore/views/template/hook/head.tpl` exists?
What is your php version?
Did you try to remove `var/cache/dev|prod`?
What is your version of starter? 
What did you chose to install it on prestashop 1.7.7.5 instead of 1.7.8?
For starter version 2.X I recommend to use prestashop 1.7.8 you can read about it in support table https://github.com/Oksydan/modern-prestashop-starter-theme#support-table

**Comment by kennethbruyninckx** [comment]
Hello,

Yes I had installed the wrong version of starter for my PS 17.7.5, additionally the head.tpl was not copied across when I uploaded all files.
The above issue has been resolved, I'll log another, subsequent issue for my next problem
