### ISSUE TITLE
Question about social title and birthdate on registration form

### ISSUE THREAD

**Issue by sparh** [Oksydan/modern-prestashop-starter-theme#91]
Hello
I am using your theme with PS 1.7.8.5
On registration form I don't see social title and birthdate field, do you have any idea why ?
I have unable birtdate in Parameters > Customers 

I saw that on your demo site social title are not displayed too ? (birtdate I don't know if you have enabled it in bo)

![image](https://user-images.githubusercontent.com/6492050/171446114-ff8c72c0-72a3-4e77-ab66-19da57a489de.png)

![image](https://user-images.githubusercontent.com/6492050/171446161-d64c3461-7ec4-40a9-86ed-ca58e8d84baa.png)

**Comment by Oksydan** [comment]
Hi @sparh 
you are right those fields are hidden.
I did it this way because like in every project we are making register form as shot as possible. 
In fact I should revert that change and leave it to decide by final developer/merchant.  

if you want to revert it in your project go to https://github.com/Oksydan/modern-prestashop-starter-theme/blob/master/templates/_partials/form-fields.tpl#L39 

And replace it with:

```smarty
{if $field.type == 'hidden'}
```

**Comment by sparh** [comment]
Many thanks

**Comment by Oksydan** [comment]
HI @sparh 
Fix has been added in [develop branch](https://github.com/Oksydan/modern-prestashop-starter-theme/commit/dc99aa2a678a0756c28e11eeb45d65ae98ce500b) and it will be available in next minor version.
